# Site settings
title: Robin Laugs
email: robinlaugs@live.nl
description: Software Engineer
url: http://robinlaugs.nl/

# Identity settings
gravatar_url: https://secure.gravatar.com/avatar/b42e5a4419fdef68eff70092b63fa8fd.png
linkedin_url: https://www.linkedin.com/in/robinlaugs/
github_url: https://github.com/Laugslander
facebook_url: https://www.facebook.com/robinlaugs
instagram_url: https://instagram.com/Laugslander

# Build settings
markdown: kramdown